import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import worker from '../server/worker.mjs';import {standings,allianceData,validateResult,validateDraws,validatePickleball,pickleScoreCodes,pickleFinalCodes,pickleAlliances,validateMedals,parseRuleDoc,validateRules,parseSchedule,validateSchedule,RULE_KEYS,safeEqual,signSession} from '../server/domain.mjs';
function database(){const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));const binding={prepare(sql){return {args:[],bind(...args){this.args=args;return this},async first(){return db.prepare(sql).get(...this.args)||null},async run(){const r=db.prepare(sql).run(...this.args);return {success:true,meta:{changes:r.changes}}},async all(){return {results:db.prepare(sql).all(...this.args)}}}},async batch(statements){db.exec('BEGIN');try{const r=[];for(const s of statements){try{r.push(await s.all())}catch{r.push(await s.run())}}db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}};return {db,binding}}
const origin='https://scoreboard.test';const SECRET='test-session-secret';
const creds={ADMIN_USER:'bateco',ADMIN_PASS:'123',SESSION_SECRET:SECRET};
const admin={Cookie:'admin='+await signSession(SECRET,Date.now()+3600000)};
function call(env,path,method='GET',body,headers={}){return worker.fetch(new Request(origin+path,{method,headers:{...(body?{'Origin':origin,'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined}),env)}
const result=(overrides={})=>({id:'00000000-0000-4000-8000-000000000001',sport_id:1,event:'Nội dung kiểm thử',participants:'Đội kiểm thử',score:'2–1',revision:0,...overrides});
const alliance=(id,gold=0,silver=0,bronze=0)=>({...allianceData.find(a=>a.id===id),gold,silver,bronze});
const medalBody=(overrides={})=>({alliance_id:1,gold:0,silver:0,bronze:0,prev:{gold:0,silver:0,bronze:0},...overrides});
test('Ranking uses gold first, then silver, then bronze, and ignores the medal total',()=>{
 const fewerButGolden=standings([alliance(1,1,0,0),alliance(2,0,5,5),alliance(3)]);
 assert.deepEqual(fewerButGolden.map(r=>r.id),[1,2,3],'mot HCV phai xep tren muoi huy chuong khong co HCV nao');
 assert.deepEqual(fewerButGolden.map(r=>r.rank),[1,2,3]);
 const sameGold=standings([alliance(1,1,0,0),alliance(2,1,2,0),alliance(3,0,0,2)]);
 assert.deepEqual(sameGold.map(r=>r.id),[2,1,3],'bang HCV thi xet tiep HCB');
 const sameGoldAndSilver=standings([alliance(1,2,1,0),alliance(2,2,1,4)]);
 assert.deepEqual(sameGoldAndSilver.map(r=>r.id),[2,1],'bang ca HCV lan HCB thi xet tiep HCD');
 const allEqual=standings([alliance(1),alliance(2),alliance(3)]);
 assert.deepEqual(allEqual.map(r=>r.rank),[1,1,1]);
 assert.ok(allEqual.every(r=>r.tied),'bang ca ba loai thi dong hang');
 assert.equal(standings([alliance(1),alliance(2,0,10,0),alliance(3)]).find(r=>r.id===2).silver,10)});


test('Input validation rejects unknown sport and oversized text, and drops medal fields',()=>{assert.throws(()=>validateResult(result({sport_id:6})));assert.throws(()=>validateResult(result({event:'x'.repeat(161)})));assert.throws(()=>validateResult(result({revision:-1})));
 const legacy=validateResult(result({gold:1,silver:2,bronze:3}));
 for(const medal of ['gold','silver','bronze'])assert.equal(medal in legacy,false,medal+' khong con thuoc hop dong ket qua')});
test('D1-compatible full flow: viewer protection, update, retry and conflicts',async()=>{const {db,binding}=database();const env={DB:binding,...creds};let response=await call(env,'/api/scoreboard');let snapshot=await response.json();assert.equal(snapshot.alliances.length,3);assert.equal(snapshot.sports.length,5);assert.equal(snapshot.results.length,0);assert.ok(snapshot.standings.every(r=>r.gold+r.silver+r.bronze===0));assert.equal((await call(env,'/api/admin/results','POST',result())).status,401);assert.equal((await call(env,'/api/admin/results','POST',result(),{Cookie:'admin=999999999999.badsig'})).status,401);assert.equal((await call(env,'/api/admin/results','POST',result(),{...admin,Origin:'https://other.test'})).status,403);
response=await call(env,'/api/admin/results','POST',result(),admin);assert.equal(response.status,200);assert.equal((await response.json()).revision,1);assert.equal((await call(env,'/api/admin/results','POST',result(),admin)).status,200);snapshot=await (await call(env,'/api/scoreboard')).json();assert.equal(snapshot.results.length,1);
assert.ok(snapshot.standings.every(r=>r.gold+r.silver+r.bronze===0));for(const medal of ['gold','silver','bronze'])assert.equal(medal in snapshot.results[0],false,medal+' khong duoc lot ra ngoai qua /api/scoreboard');
assert.equal((await call(env,'/api/admin/results','POST',result({id:'00000000-0000-4000-8000-000000000002'}),admin)).status,409);const update=result({revision:1,score:'3-0'});assert.equal((await call(env,'/api/admin/results','POST',update,admin)).status,200);assert.equal((await call(env,'/api/admin/results','POST',update,admin)).status,200);assert.equal((await call(env,'/api/admin/results','POST',result({revision:1,score:'khac'}),admin)).status,409);snapshot=await (await call(env,'/api/scoreboard')).json();assert.equal(snapshot.results[0].revision,2);assert.equal(snapshot.results[0].score,'3-0');assert.equal((await call(env,'/api/admin/results','POST',result(),{Cookie:'admin='+await signSession('wrong-secret',Date.now()+3600000)})).status,401);db.close()});
test('Storage outage returns unavailable instead of fabricated zero scores',async()=>{const r=await call({},'/api/scoreboard');assert.equal(r.status,503);assert.ok((await r.json()).error)});
test('Delete requires admin and current revision; preserves other results',async()=>{const {db,binding}=database();const env={DB:binding,...creds};await call(env,'/api/admin/results','POST',result(),admin);await call(env,'/api/admin/results','POST',result({id:'00000000-0000-4000-8000-000000000002',event:'Other event'}),admin);const deletion={id:result().id,revision:1};assert.equal((await call(env,'/api/admin/results','DELETE',deletion)).status,401);assert.equal((await call(env,'/api/admin/results','DELETE',deletion,{Cookie:'admin=not-a-token'})).status,401);assert.equal((await call(env,'/api/admin/results','DELETE',deletion,{...admin,Origin:'https://other.test'})).status,403);assert.equal((await call(env,'/api/admin/results','DELETE',{...deletion,revision:2},admin)).status,409);assert.equal((await call(env,'/api/admin/results','DELETE',deletion,admin)).status,200);assert.equal((await call(env,'/api/admin/results','DELETE',deletion,admin)).status,200);const snapshot=await (await call(env,'/api/scoreboard')).json();assert.equal(snapshot.results.length,1);assert.equal(snapshot.results[0].event,'Other event');assert.equal((await call(env,'/api/admin/results','POST',result({revision:1}),admin)).status,409);db.close()});
test('Login issues an HttpOnly cookie only for the right credentials',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 const good=await call(env,'/api/admin/login','POST',{user:'bateco',pass:'123'});assert.equal(good.status,200);
 const setCookie=good.headers.get('Set-Cookie');assert.match(setCookie,/^admin=\d+\./);assert.match(setCookie,/HttpOnly/);assert.match(setCookie,/SameSite=Strict/);
 const bad=await call(env,'/api/admin/login','POST',{user:'bateco',pass:'sai'});assert.equal(bad.status,401);assert.equal(bad.headers.get('Set-Cookie'),null);
 assert.equal((await call(env,'/api/admin/login','POST',{user:'khac',pass:'123'})).status,401);
 assert.equal((await call(env,'/api/admin/login','POST',{user:'bateco',pass:'123'},{Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/login','GET')).status,405);
 // The cookie just issued must actually authorise a write.
 assert.equal((await call(env,'/api/admin/results','POST',result(),{Cookie:setCookie.split(';')[0]})).status,200);
 assert.match((await call(env,'/api/admin/logout','POST',{},{Origin:origin})).headers.get('Set-Cookie'),/Max-Age=0/);
 assert.equal((await call(env,'/api/admin/logout','POST',{},{Origin:'https://other.test'})).status,403);db.close()});
test('Session cookies are rejected when expired, resigned or malformed',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 const expired='admin='+await signSession(SECRET,Date.now()-1);
 assert.equal((await call(env,'/api/admin/session','GET',undefined,{Cookie:expired})).status,401);
 const valid=await signSession(SECRET,Date.now()+3600000);
 const tampered='admin='+valid.slice(0,-1)+(valid.endsWith('A')?'B':'A');
 assert.equal((await call(env,'/api/admin/session','GET',undefined,{Cookie:tampered})).status,401);
 for(const raw of ['admin=','admin=abc','admin=.sig','admin=12x.sig','other=x'])
  assert.equal((await call(env,'/api/admin/session','GET',undefined,{Cookie:raw})).status,401);
 assert.equal((await call(env,'/api/admin/session','GET',undefined,admin)).status,200);
 // Missing secret must fail closed, never open.
 assert.equal((await call({DB:binding},'/api/admin/session','GET',undefined,admin)).status,401);db.close()});
test('safeEqual compares without leaking length or position',()=>{assert.equal(safeEqual('abc','abc'),true);assert.equal(safeEqual('abc','abd'),false);assert.equal(safeEqual('abc','abcd'),false);assert.equal(safeEqual('',''),true);assert.equal(safeEqual(undefined,'x'),false);assert.equal(safeEqual(null,null),true)});
test('Draw validation rejects bad sport, wrong column count, oversized cells and drops blank rows',()=>{
 assert.throws(()=>validateDraws({sport_id:6,rows:[]}));
 assert.throws(()=>validateDraws({sport_id:1,rows:[['a','b','c']]}));
 assert.throws(()=>validateDraws({sport_id:1,rows:[['a','b','c','d','e']]}));
 assert.throws(()=>validateDraws({sport_id:1,rows:[['x'.repeat(201),'','','']]}));
 assert.throws(()=>validateDraws({sport_id:1,rows:Array.from({length:61},()=>['a','','',''])}));
 assert.throws(()=>validateDraws({sport_id:1,rows:[[1,2,3,4]]}));
 assert.deepEqual(validateDraws({sport_id:1,rows:[['  A  ','B','',''],['','','','']]}).rows,[['A','B','','']]);
 assert.deepEqual(validateDraws({sport_id:2,rows:[]}),{sport_id:2,rows:[]})});
test('Draws require a session, replace the whole set per sport and leave other sports intact',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 const body={sport_id:1,rows:[['Bảng A','TP vs BP','Lượt 1','08:15']]};
 assert.equal((await call(env,'/api/admin/draws','POST',body)).status,401);
 assert.equal((await call(env,'/api/admin/draws','POST',body,{...admin,Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/draws','POST',{sport_id:9,rows:[]},admin)).status,400);
 // Writing on a database that has never been seeded must still satisfy the sports foreign key.
 assert.equal((await call(env,'/api/admin/draws','POST',{sport_id:1,rows:[['a','b','c','d'],['e','f','g','h'],['i','j','k','l']]},admin)).status,200);
 assert.equal((await call(env,'/api/admin/draws','POST',{sport_id:2,rows:[['Nữ 1.500m','Lan','Lượt 1','09:00']]},admin)).status,200);
 let snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.draws.filter(d=>d.sport_id===1).length,3);
 assert.equal(snap.draws.filter(d=>d.sport_id===2).length,1);
 assert.deepEqual(snap.draws.filter(d=>d.sport_id===1).map(d=>d.ord),[0,1,2]);
 // Replacing sport 1 must not touch sport 2.
 assert.equal((await call(env,'/api/admin/draws','POST',{sport_id:1,rows:[['chi','con','mot','dong']]},admin)).status,200);
 snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.draws.filter(d=>d.sport_id===1).length,1);
 assert.equal(snap.draws.filter(d=>d.sport_id===2).length,1);
 // Empty rows clears just that sport.
 assert.equal((await call(env,'/api/admin/draws','POST',{sport_id:1,rows:[]},admin)).status,200);
 snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.draws.filter(d=>d.sport_id===1).length,0);
 assert.equal(snap.draws.filter(d=>d.sport_id===2).length,1);db.close()});
test('Missing deploy config is reported as a server problem, not a wrong password',async()=>{const {db,binding}=database();
 for(const absent of ['ADMIN_USER','ADMIN_PASS','SESSION_SECRET']){
  const env={DB:binding,...creds};delete env[absent];
  const r=await call(env,'/api/admin/login','POST',{user:'bateco',pass:'123'});
  assert.equal(r.status,503,absent+' phải trả 503 thay vì 401');
  assert.equal(r.headers.get('Set-Cookie'),null);
  assert.doesNotMatch((await r.json()).error,/mật khẩu không đúng/)}
 // Correct credentials with full config still work, so the guard did not over-trigger.
 assert.equal((await call({DB:binding,...creds},'/api/admin/login','POST',{user:'bateco',pass:'123'})).status,200);db.close()});
const emptyPairs=()=>({A:[0,1,2,3,4].map(()=>['','','']),B:[0,1,2,3,4].map(()=>['','',''])});
const pickle=(overrides={})=>({sport_id:3,pairs:emptyPairs(),scores:Object.fromEntries(pickleScoreCodes.map(c=>[c,''])),groups:{A:{first:null,second:null},B:{first:null,second:null}},finals:Object.fromEntries(pickleFinalCodes.map(c=>[c,{score:'',winner:null}])),...overrides});
test('Pickleball validation enforces 20 group scores, the exact 4 final codes and a valid winner',()=>{
 assert.equal(pickleScoreCodes.length,20);
 assert.throws(()=>validatePickleball(pickle({sport_id:6})));
 assert.throws(()=>validatePickleball(pickle({scores:{}})));
 const short={...pickle().scores};delete short.R5C4;
 assert.throws(()=>validatePickleball(pickle({scores:short})));
 assert.throws(()=>validatePickleball(pickle({scores:{...pickle().scores,R6C1:''}})));
 assert.throws(()=>validatePickleball(pickle({scores:{...pickle().scores,R1C1:'x'.repeat(41)}})));
 assert.throws(()=>validatePickleball(pickle({scores:{...pickle().scores,R1C1:11}})));
 const missingFinal={...pickle().finals};delete missingFinal.BRONZE;
 assert.throws(()=>validatePickleball(pickle({finals:missingFinal})));
 assert.throws(()=>validatePickleball(pickle({finals:{...pickle().finals,F:{score:'',winner:null}}})));
 assert.throws(()=>validatePickleball(pickle({finals:{...pickle().finals,GOLD:{score:'',winner:3}}})));
 assert.throws(()=>validatePickleball(pickle({finals:{...pickle().finals,GOLD:{score:'x'.repeat(41),winner:null}}})));
 const ok=validatePickleball(pickle({scores:{...pickle().scores,R1C1:' 11-7 '},finals:{...pickle().finals,SF1:{score:' 11-9 ',winner:1}}}));
 assert.equal(ok.scores.R1C1,'11-7');
 assert.equal(ok.finals.SF1.score,'11-9');
 assert.equal(ok.finals.SF1.winner,1);
 assert.equal(ok.finals.GOLD.winner,null)});
test('Pickleball validation rejects a group whose first and second are the same pair',()=>{
 assert.throws(()=>validatePickleball(pickle({groups:{A:{first:2,second:2},B:{first:null,second:null}}})));
 assert.throws(()=>validatePickleball(pickle({groups:{A:{first:5,second:0},B:{first:null,second:null}}})));
 assert.throws(()=>validatePickleball(pickle({groups:{A:{first:-1,second:0},B:{first:null,second:null}}})));
 assert.throws(()=>validatePickleball(pickle({groups:{A:{first:1.5,second:0},B:{first:null,second:null}}})));
 assert.throws(()=>validatePickleball(pickle({groups:{A:{first:null,second:2},B:{first:null,second:null}}})));
 assert.throws(()=>validatePickleball(pickle({groups:{A:{first:null,second:null}}})));
 const ok=validatePickleball(pickle({groups:{A:{first:2,second:3},B:{first:null,second:null}}}));
 assert.deepEqual(ok.groups.A,{first:2,second:3});
 assert.deepEqual(ok.groups.B,{first:null,second:null})});
test('Pickleball validation keeps 05 pairs per group and accepts replacing only one member',()=>{
 assert.throws(()=>validatePickleball(pickle({pairs:{A:emptyPairs().A}})));
 assert.throws(()=>validatePickleball(pickle({pairs:{A:emptyPairs().A.slice(0,4),B:emptyPairs().B}})));
 assert.throws(()=>validatePickleball(pickle({pairs:{A:[...emptyPairs().A,['','','']],B:emptyPairs().B}})));
 const twoCells={...emptyPairs()};twoCells.A=[['a','b'],...emptyPairs().A.slice(1)];
 assert.throws(()=>validatePickleball(pickle({pairs:twoCells})));
 const tooLong={...emptyPairs()};tooLong.A=[['x'.repeat(61),'b',''],...emptyPairs().A.slice(1)];
 assert.throws(()=>validatePickleball(pickle({pairs:tooLong})));
 const badTeam={...emptyPairs()};badTeam.A=[['a','b','XX'],...emptyPairs().A.slice(1)];
 assert.throws(()=>validatePickleball(pickle({pairs:badTeam})));
 const notString={...emptyPairs()};notString.A=[[1,'b',''],...emptyPairs().A.slice(1)];
 assert.throws(()=>validatePickleball(pickle({pairs:notString})));
 const onlyFirst={...emptyPairs()};onlyFirst.A=[[' Dự Bị ','',''],...emptyPairs().A.slice(1)];
 const ok=validatePickleball(pickle({pairs:onlyFirst}));
 assert.deepEqual(ok.pairs.A[0],['Dự Bị','',''],'thay mot thanh vien, nguoi con lai giu ten mac dinh');
 for(const t of pickleAlliances)assert.equal(validatePickleball(pickle({pairs:{...emptyPairs(),A:[['a','b',t],...emptyPairs().A.slice(1)]}})).pairs.A[0][2],t,'nhan lien minh hop le phai duoc giu lai trong tai lieu luu');
 const keep=validatePickleball(pickle({pairs:{...emptyPairs(),A:[['x'.repeat(60),'b',''],...emptyPairs().A.slice(1)]}}));
 assert.equal(keep.pairs.A[0][0].length,60,'dung 60 ky tu la bien hop le, khong duoc chan');
 const bare={...pickle()};delete bare.pairs;
 assert.throws(()=>validatePickleball(bare),'thieu han truong pairs phai bi tu choi')});
test('Pickleball route requires admin and keeps exactly one row per sport',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/bracket','POST',pickle())).status,401);
 assert.equal((await call(env,'/api/admin/bracket','POST',pickle(),{Cookie:'admin=not-a-token'})).status,401);
 assert.equal((await call(env,'/api/admin/bracket','POST',pickle(),{...admin,Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/bracket','POST',pickle({scores:{}}),admin)).status,400);
 assert.equal((await call(env,'/api/admin/bracket','POST',pickle(),admin)).status,200);
 let snapshot=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snapshot.brackets.length,1);
 assert.equal(snapshot.brackets[0].sport_id,3);
 assert.equal(Object.keys(snapshot.brackets[0].data.scores).length,20);
 assert.equal((await call(env,'/api/admin/bracket','POST',pickle({scores:{...pickle().scores,R1C1:'11-5'},groups:{A:{first:0,second:1},B:{first:null,second:null}}}),admin)).status,200);
 snapshot=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snapshot.brackets.length,1);
 assert.equal(snapshot.brackets[0].data.scores.R1C1,'11-5');
 assert.equal(snapshot.brackets[0].data.groups.A.first,0);
 db.close()});
test('Scoreboard keeps serving standings when the bracket table cannot be read',async()=>{const {db,binding}=database();
 // Mô phỏng production chưa migrate: bảng brackets chưa tồn tại.
 db.exec('DROP TABLE brackets');
 const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/results','POST',result(),admin)).status,200);
 const response=await call(env,'/api/scoreboard');
 assert.equal(response.status,200);
 const snapshot=await response.json();
 assert.deepEqual(snapshot.brackets,[]);
 assert.equal(snapshot.results.length,1);
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:1,gold:1}),admin)).status,200);
 const after=await (await call(env,'/api/scoreboard')).json();
 assert.equal(after.standings[0].id,1);
 assert.equal(after.standings[0].gold,1);
 db.close()});
test('Scoreboard tolerates a row still holding the old knockout shape',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 await call(env,'/api/scoreboard');
 db.prepare('INSERT INTO brackets (sport_id,data,updated_at) VALUES (3,?,?)').run(JSON.stringify({teams:['AB','CD','EF','GH','JK','LM','XC','VB'],matches:{QF1:{score:'2-1',winner:1}}}),new Date().toISOString());
 const response=await call(env,'/api/scoreboard');
 assert.equal(response.status,200);
 const snapshot=await response.json();
 assert.equal(snapshot.brackets.length,1);
 assert.equal(snapshot.brackets[0].data.scores,undefined,'du lieu so do cu khong duoc gia vo la vong bang');
 db.close()});
test('Medal validation rejects unknown alliance, negative, fractional and oversized totals',()=>{
 assert.throws(()=>validateMedals(medalBody({alliance_id:0})));
 assert.throws(()=>validateMedals(medalBody({alliance_id:4})));
 assert.throws(()=>validateMedals(medalBody({alliance_id:'1'})));
 assert.throws(()=>validateMedals(medalBody({gold:-1})));
 assert.throws(()=>validateMedals(medalBody({silver:1.5})));
 assert.throws(()=>validateMedals(medalBody({bronze:1000})));
 assert.throws(()=>validateMedals(medalBody({gold:null})));
 assert.throws(()=>validateMedals([]));
 assert.throws(()=>validateMedals(medalBody({prev:undefined})),undefined,'thiếu số liệu trước đó thì không thể phát hiện ghi đè');
 assert.throws(()=>validateMedals(medalBody({prev:{gold:0,silver:0}})));
 assert.throws(()=>validateMedals(medalBody({prev:{gold:-1,silver:0,bronze:0}})));
 assert.deepEqual(validateMedals(medalBody({alliance_id:3,gold:7,silver:0,bronze:12})),{alliance_id:3,gold:7,silver:0,bronze:12,prev:{gold:0,silver:0,bronze:0}})});
test('Medals require a session, replace one alliance total and leave the others intact',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 const body=medalBody({alliance_id:2,gold:3,silver:1,bronze:0});
 assert.equal((await call(env,'/api/admin/medals','POST',body)).status,401);
 assert.equal((await call(env,'/api/admin/medals','POST',body,{Cookie:'admin=not-a-token'})).status,401);
 assert.equal((await call(env,'/api/admin/medals','POST',body,{...admin,Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:9}),admin)).status,400);
 assert.equal((await call(env,'/api/admin/medals','POST',body,admin)).status,200);
 let snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.standings.find(a=>a.id===2).gold,3);
 assert.equal(snap.standings.find(a=>a.id===2).silver,1);
 assert.ok(snap.standings.filter(a=>a.id!==2).every(a=>a.gold+a.silver+a.bronze===0),'ghi mot lien minh khong duoc dung hai lien minh con lai');
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:2,gold:0,silver:0,bronze:5,prev:{gold:3,silver:1,bronze:0}}),admin)).status,200);
 snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.standings.find(a=>a.id===2).gold,0,'ghi de phai thay ca ba loai, khong cong don');
 assert.equal(snap.standings.find(a=>a.id===2).bronze,5);db.close()});
test('Medals can be written on a database that has never been seeded',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:1,gold:2}),admin)).status,200);
 const snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.standings.find(a=>a.id===1).gold,2,'UPDATE tren DB chua seed se khop 0 dong neu thieu seed()');db.close()});
test('Medal totals refuse a stale overwrite instead of silently discarding the other admin\'s entry',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:1,gold:3,silver:2,bronze:1}),admin)).status,200);
 const stale=medalBody({alliance_id:1,gold:3,silver:2,bronze:2,prev:{gold:3,silver:2,bronze:1}});
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:1,gold:4,silver:2,bronze:1,prev:{gold:3,silver:2,bronze:1}}),admin)).status,200);
 const conflict=await call(env,'/api/admin/medals','POST',stale,admin);
 assert.equal(conflict.status,409,'form mở từ trước không được ghi đè số liệu vừa nhập ở nơi khác');
 assert.match((await conflict.json()).error,/vừa được sửa ở nơi khác/);
 let snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.standings.find(a=>a.id===1).gold,4,'HCV của lần ghi sau phải còn nguyên');
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:1,gold:4,silver:2,bronze:2,prev:{gold:4,silver:2,bronze:1}}),admin)).status,200,'nhập lại với số liệu mới phải thành công');
 snap=await (await call(env,'/api/scoreboard')).json();
 assert.equal(snap.standings.find(a=>a.id===1).bronze,2);db.close()});
function clientConst(name){const L=fs.readFileSync('dist/app.js','utf8').split(/\r?\n/);const start=L.findIndex(l=>l.startsWith('const '+name+'='));
 if(start<0)throw Error('khong tim thay '+name+' trong dist/app.js');
 for(let end=start;end<L.length;end++){try{return new Function(L.slice(start,end+1).join('\n')+';return '+name)()}catch{}}
 throw Error('khong doc duoc '+name+' tu dist/app.js')}
const ruleDoc=(overrides={})=>({key:'tug',title:'Kéo co',quick:'Thành phần | 10 VĐV',notes:'Không thay người',full:'LUẬT THI ĐẤU KÉO CO',...overrides});
test('Rule text parsing keeps blocks in order and groups adjacent pipe rows into one table',()=>{
 const d=parseRuleDoc({title:' Kéo co ',quick:'Thành phần | 10 VĐV\n\nThể thức | Vòng tròn',notes:'Ý một\n\nÝ hai',full:'LUẬT THI ĐẤU KÉO CO\n1. Thành phần\nMỗi đội 10 VĐV.\nNội dung | Quy định\nSố hiệp | 01\n\nSau bảng'});
 assert.equal(d.title,'Kéo co');
 assert.deepEqual(d.quick,[['Thành phần','10 VĐV'],['Thể thức','Vòng tròn']]);
 assert.deepEqual(d.notes,['Ý một','Ý hai']);
 assert.deepEqual(d.blocks,[{type:'p',text:'LUẬT THI ĐẤU KÉO CO'},{type:'p',text:'1. Thành phần'},{type:'p',text:'Mỗi đội 10 VĐV.'},{type:'table',rows:[['Nội dung','Quy định'],['Số hiệp','01']]},{type:'p',text:'Sau bảng'}]);
 assert.deepEqual(parseRuleDoc({title:'x',quick:'',notes:'',full:'A | B\n\nC | D'}).blocks,[{type:'table',rows:[['A','B']]},{type:'table',rows:[['C','D']]}],'dòng trống phải cắt thành hai bảng riêng');
 assert.deepEqual(parseRuleDoc({title:'x',quick:'',notes:'',full:''}).blocks,[])});
test('Rule validation rejects unknown document, wrong types, oversized text and malformed table rows',()=>{
 assert.deepEqual(RULE_KEYS,['tug','men','women','relay','pickle','aoe','football']);
 assert.throws(()=>validateRules(ruleDoc({key:'khong-co'})));
 assert.throws(()=>validateRules(ruleDoc({key:undefined})));
 assert.throws(()=>validateRules(ruleDoc({title:''})));
 assert.throws(()=>validateRules(ruleDoc({title:'x'.repeat(121)})));
 assert.throws(()=>validateRules(ruleDoc({full:123})));
 assert.throws(()=>validateRules(ruleDoc({full:'x'.repeat(16001)})));
 assert.throws(()=>validateRules(ruleDoc({quick:'thiếu dấu gạch đứng'})),undefined,'Thông tin nhanh bắt buộc dạng nhãn | nội dung');
 assert.throws(()=>validateRules(ruleDoc({full:'A | B | C'})),undefined,'dòng bảng ba ô phải báo lỗi thay vì âm thầm cắt bớt');
 assert.throws(()=>validateRules(ruleDoc({full:'Dòng một\nDòng hai\nA | B | C'})),/dòng 3/,'lỗi phải chỉ ra dòng nào sai, không bắt admin dò 300 dòng');
 assert.throws(()=>validateRules(ruleDoc({quick:'ổn | rồi\nthiếu dấu gạch'})),/dòng 2/);
 assert.throws(()=>validateRules([]));
 const ok=validateRules(ruleDoc());assert.equal(ok.key,'tug');assert.equal(ok.full,'LUẬT THI ĐẤU KÉO CO')});
test('Serialising the built-in rules and parsing them back reproduces every document',()=>{
 const fullRules=clientConst('fullRules'),ruleSummaries=clientConst('ruleSummaries');
 const blocksToText=clientConst('blocksToText'),pairsToText=clientConst('pairsToText');
 assert.equal(Object.keys(fullRules).length,6);
 assert.equal(Object.keys(ruleSummaries).length,6);
 for(const [k,base] of Object.entries(ruleSummaries)){
  const d=parseRuleDoc({title:base.title,quick:pairsToText(base.quick),notes:base.notes.join('\n'),full:blocksToText(fullRules[base.key])});
  assert.equal(d.title,base.title,k+': tên luật lệch');
  assert.deepEqual(d.quick,base.quick,k+': Thông tin nhanh không round-trip');
  assert.deepEqual(d.notes,base.notes,k+': Lưu ý quan trọng không round-trip');
  assert.deepEqual(d.blocks,fullRules[base.key],k+': toàn văn luật không round-trip')}});
test('Rules require a session and keep exactly one row per document',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc())).status,401);
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc(),{Cookie:'admin=not-a-token'})).status,401);
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc(),{...admin,Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc({key:'khong-co'}),admin)).status,400);
 assert.deepEqual(await (await call(env,'/api/rules')).json(),{rules:[]},'chưa nhập gì thì không có dòng nào để phủ lên mặc định');
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc({full:'1. Mục\nNội dung | Quy định\nSố hiệp | 01'}),admin)).status,200);
 let r=(await (await call(env,'/api/rules','GET',undefined,admin)).json()).rules;
 assert.equal(r.length,1);assert.equal(r[0].key,'tug');
 assert.deepEqual(r[0].blocks,[{type:'p',text:'1. Mục'},{type:'table',rows:[['Nội dung','Quy định'],['Số hiệp','01']]}]);
 assert.equal(r[0].raw.full,'1. Mục\nNội dung | Quy định\nSố hiệp | 01','văn bản thô phải trả về nguyên vẹn để form nạp lại');
 const publicRules=(await (await call(env,'/api/rules')).json()).rules;
 assert.equal('raw' in publicRules[0],false,'khách xem trang không cần bản thô, nó nhân đôi payload');
 assert.ok(publicRules[0].blocks.length>0,'khách vẫn phải nhận đủ nội dung đã parse');
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc({title:'Kéo co sửa lần hai'}),admin)).status,200);
 r=(await (await call(env,'/api/rules','GET',undefined,admin)).json()).rules;
 assert.equal(r.length,1,'ghi đè phải thay cả dòng, không để lại bản ghi thứ hai');
 assert.equal(r[0].title,'Kéo co sửa lần hai');
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc({key:'football',title:'Bóng đá Nam'}),admin)).status,200);
 assert.equal((await (await call(env,'/api/rules')).json()).rules.length,2);db.close()});
test('Deleting a rule document restores the built-in default instead of leaving a permanent override',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/rules','POST',ruleDoc(),admin)).status,200);
 assert.equal((await call(env,'/api/admin/rules','DELETE',{key:'tug'})).status,401);
 assert.equal((await call(env,'/api/admin/rules','DELETE',{key:'tug'},{...admin,Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/rules','DELETE',{key:'khong-co'},admin)).status,400);
 assert.equal((await (await call(env,'/api/rules')).json()).rules.length,1);
 assert.equal((await call(env,'/api/admin/rules','DELETE',{key:'tug'},admin)).status,200);
 assert.deepEqual(await (await call(env,'/api/rules')).json(),{rules:[]},'xóa xong phải không còn dòng nào để trang lùi về nội dung nướng sẵn');
 assert.equal((await call(env,'/api/admin/rules','DELETE',{key:'tug'},admin)).status,200,'xóa lại lần nữa vẫn phải thành công');db.close()});
test('A missing rules table never takes the scoreboard down',async()=>{const {db,binding}=database();
 db.exec('DROP TABLE rules');
 const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/medals','POST',medalBody({alliance_id:2,gold:3}),admin)).status,200);
 const response=await call(env,'/api/scoreboard');
 assert.equal(response.status,200);
 const snapshot=await response.json();
 assert.equal(snapshot.standings[0].id,2);
 assert.equal(snapshot.standings[0].gold,3);
 const rules=await call(env,'/api/rules');
 assert.equal(rules.status,200,'luật hỏng phải trả danh sách rỗng, không phải 500');
 assert.deepEqual(await rules.json(),{rules:[]});db.close()});
const scheduleText=['07:30 – 08:00 | Tập trung','14:00 – 17:30 | Bóng đá Nam | BATECO CUP'].join('\n');
test('Schedule text parsing keeps row order, treats the third cell as an optional label and skips blank lines',()=>{
 assert.deepEqual(parseSchedule(scheduleText),[['07:30 – 08:00','Tập trung'],['14:00 – 17:30','Bóng đá Nam','BATECO CUP']]);
 assert.deepEqual(parseSchedule('  a | b  \n\n\n  c | d  '),[['a','b'],['c','d']],'khoảng trắng và dòng trống không được sinh ra dòng rỗng');
 assert.deepEqual(parseSchedule('a | b |'),[['a','b']],'cột nhãn để trống thì bỏ nhãn chứ không báo lỗi');
 assert.deepEqual(parseSchedule('a | b |   '),[['a','b']]);
 assert.deepEqual(parseSchedule(''),[]);
 assert.deepEqual(parseSchedule(null),[])});
test('Schedule parsing rejects malformed rows and names the offending line',()=>{
 assert.throws(()=>parseSchedule('thiếu dấu gạch đứng'),/dòng 1/,'một ô không đủ thành một mục lịch trình');
 assert.throws(()=>parseSchedule('a | b | c | d'),/dòng 1/,'bốn ô phải báo lỗi thay vì âm thầm cắt bớt');
 assert.throws(()=>parseSchedule(' | b'),/dòng 1/,'thiếu giờ');
 assert.throws(()=>parseSchedule('a | '),/dòng 1/,'thiếu tên hoạt động');
 assert.throws(()=>parseSchedule('a | b\nc | d\nsai'),/dòng 3/,'lỗi phải chỉ ra dòng nào sai, không bắt admin dò cả bảng')});
test('Schedule validation guards type, size and row count',()=>{
 assert.throws(()=>validateSchedule(null));
 assert.throws(()=>validateSchedule([]));
 assert.throws(()=>validateSchedule({text:123}));
 assert.throws(()=>validateSchedule({text:''}),undefined,'lịch trình rỗng sẽ xoá sạch mục trên trang nên phải chặn');
 assert.throws(()=>validateSchedule({text:'\n\n  \n'}),undefined,'toàn dòng trắng cũng là rỗng');
 assert.throws(()=>validateSchedule({text:'a | b\n'.repeat(41)}),/40 dòng/);
 assert.throws(()=>validateSchedule({text:'a | '+'x'.repeat(4000)}),/4000 ký tự/);
 const ok=validateSchedule({text:scheduleText});
 assert.equal(ok.text,scheduleText,'văn bản thô phải được giữ nguyên để admin sửa tiếp');
 assert.equal(ok.rows.length,2)});
test('Serialising the built-in schedule and parsing it back reproduces every row',()=>{
 const schedule=clientConst('schedule');
 assert.equal(schedule.length,9);
 const text=schedule.map(r=>r.join(' | ')).join('\n');
 assert.deepEqual(parseSchedule(text),schedule,'lịch trình nướng sẵn phải round-trip qua đúng định dạng admin nhập')});
test('The built-in schedule carries exactly one label, on the football row',()=>{
 const schedule=clientConst('schedule');
 assert.equal(schedule.length,9);
 const labelled=schedule.filter(r=>r.length===3);
 assert.equal(labelled.length,1,'đúng một mục mang nhãn, như bản đang chạy');
 assert.deepEqual(labelled[0],['14:00 – 17:30','Bóng đá Nam – BATECO CUP','BATECO CUP']);
 for(const [time,name] of schedule){
  assert.ok(time.trim(),'mọi mục phải có giờ');
  assert.ok(name.trim(),'mọi mục phải có tên hoạt động')}});
test('Every schedule cell reaches the page through the HTML escaper',()=>{
 const line=fs.readFileSync('dist/app.js','utf8').split(/\r?\n/).find(l=>l.startsWith('function renderSchedule()'));
 assert.ok(line,'không tìm thấy renderSchedule trong dist/app.js');
 const body=line.slice(line.indexOf('innerHTML='));
 for(const cell of ['t','n','tag'])
  assert.match(body,new RegExp('officialText\\('+cell+'\\)'),`ô ${cell} phải đi qua officialText, nếu không admin nhập được HTML thẳng vào trang`);
 assert.doesNotMatch(body,/\$\{(t|n|tag)\}/,'không ô nào được nhúng thẳng vào HTML')});
test('Schedule requires a session and keeps exactly one row',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:scheduleText})).status,401);
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:scheduleText},{Cookie:'admin=not-a-token'})).status,401);
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:scheduleText},{...admin,Origin:'https://other.test'})).status,403);
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:'sai định dạng'},admin)).status,400);
 assert.deepEqual(await (await call(env,'/api/schedule')).json(),{schedule:null},'chưa nhập gì thì không có gì phủ lên mặc định');
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:scheduleText},admin)).status,200);
 const asAdmin=(await (await call(env,'/api/schedule','GET',undefined,admin)).json()).schedule;
 assert.equal(asAdmin.text,scheduleText,'admin cần bản thô để sửa tiếp');
 assert.deepEqual(asAdmin.rows[1],['14:00 – 17:30','Bóng đá Nam','BATECO CUP']);
 const asGuest=(await (await call(env,'/api/schedule')).json()).schedule;
 assert.equal('text' in asGuest,false,'khách xem trang không cần bản thô, nó nhân đôi payload');
 assert.equal(asGuest.rows.length,2);
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:'09:00 | Chỉ một mục'},admin)).status,200);
 assert.equal((await (await call(env,'/api/schedule')).json()).schedule.rows.length,1,'lưu lần hai phải thay thế chứ không cộng dồn');
 assert.equal(db.prepare('SELECT COUNT(*) c FROM schedule').get().c,1,'bảng chỉ được giữ đúng một dòng');db.close()});
test('Deleting the schedule restores the built-in default instead of leaving a permanent override',async()=>{const {db,binding}=database();const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/admin/schedule','POST',{text:scheduleText},admin)).status,200);
 assert.equal((await call(env,'/api/admin/schedule','DELETE',{})).status,401);
 assert.equal((await call(env,'/api/admin/schedule','DELETE',{},{...admin,Origin:'https://other.test'})).status,403);
 assert.notEqual((await (await call(env,'/api/schedule')).json()).schedule,null);
 assert.equal((await call(env,'/api/admin/schedule','DELETE',{},admin)).status,200);
 assert.deepEqual(await (await call(env,'/api/schedule')).json(),{schedule:null},'xóa xong trang phải lùi về lịch trình nướng sẵn');
 assert.equal((await call(env,'/api/admin/schedule','DELETE',{},admin)).status,200,'xóa lại lần nữa vẫn phải thành công');db.close()});
test('A missing schedule table never takes the scoreboard down',async()=>{const {db,binding}=database();
 db.exec('DROP TABLE schedule');
 const env={DB:binding,...creds};
 assert.equal((await call(env,'/api/scoreboard')).status,200,'bảng điểm không được phụ thuộc vào lịch trình');
 const sched=await call(env,'/api/schedule');
 assert.equal(sched.status,200);
 assert.deepEqual(await sched.json(),{schedule:null},'lịch trình hỏng thì trang lùi về mặc định, không báo lỗi cho người xem');db.close()});
