export const allianceData=[{id:1,name:'TIÊN PHONG',members:'CN1 + Cung ứng Đấu thầu + VP + Khối KHCTY'},{id:2,name:'BỨT PHÁ',members:'CN2 + BTC Quốc An + HO (Nhân sự + Kế toán + KSNB + Tài chính)'},{id:3,name:'CHINH PHỤC',members:'CN3 + BESIP + CNTT + Distributor + BTC Lai Châu + MJChem'}];
export const sportData=[{id:1,name:'Đoàn kết',discipline:'Kéo co 10v10'},{id:2,name:'Tốc độ',discipline:'Điền kinh'},{id:3,name:'Phối hợp',discipline:'Pickleball'},{id:4,name:'Esport',discipline:'PC'},{id:5,name:'Bóng đá Nam',discipline:'BATECO CUP'}];
export function standings(alliances,results){const rows=alliances.map(a=>({...a,gold:0,silver:0,bronze:0}));for(const r of results)for(const medal of ['gold','silver','bronze']){const a=rows.find(a=>a.id===r[medal]);if(a)a[medal]++}rows.sort((a,b)=>b.gold-a.gold||b.silver-a.silver||b.bronze-a.bronze||a.id-b.id);let rank=1;return rows.map((a,i)=>{if(i&&['gold','silver','bronze'].some(k=>a[k]!==rows[i-1][k]))rank=i+1;return {...a,rank,tied:rows.some(b=>b.id!==a.id&&['gold','silver','bronze'].every(k=>b[k]===a[k]))}})}
export function validateResult(body){if(!body||typeof body!=='object'||Array.isArray(body))throw Error('Dữ liệu không hợp lệ.');const r={};if(typeof body.id!=='string'||!/^[-a-zA-Z0-9]{16,80}$/.test(body.id))throw Error('Mã kết quả không hợp lệ.');r.id=body.id;if(!Number.isInteger(body.sport_id)||body.sport_id<1||body.sport_id>5)throw Error('Vui lòng chọn môn thi đấu.');r.sport_id=body.sport_id;for(const [field,label,max] of [['event','Trận/Phần thi',160],['participants','Đội/VĐV',1000],['score','Kết quả',1000]]){if(typeof body[field]!=='string'||!body[field].trim()||body[field].trim().length>max)throw Error(`${label}: cần nhập từ 1 đến ${max} ký tự.`);r[field]=body[field].trim()}for(const medal of ['gold','silver','bronze']){const v=body[medal];if(v!==null&&(!Number.isInteger(v)||v<1||v>3))throw Error('Liên minh nhận huy chương không hợp lệ.');r[medal]=v}if(!Number.isInteger(body.revision)||body.revision<0)throw Error('Phiên bản kết quả không hợp lệ.');r.revision=body.revision;return r}
export function safeEqual(a,b){a=String(a??'');b=String(b??'');if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
function base64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sign(secret,payload){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return base64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload))))}
export async function signSession(secret,exp){return exp+'.'+await sign(secret,String(exp))}
export async function verifySession(secret,token,nowMs){if(!secret||typeof token!=='string')return false;const dot=token.indexOf('.');if(dot<1)return false;const exp=token.slice(0,dot),sig=token.slice(dot+1);if(!/^\d{1,15}$/.test(exp)||Number(exp)<=nowMs||!sig)return false;return safeEqual(sig,await sign(secret,exp))}
export function validateDraws(body){if(!body||typeof body!=='object'||Array.isArray(body))throw Error('Dữ liệu không hợp lệ.');if(!Number.isInteger(body.sport_id)||body.sport_id<1||body.sport_id>5)throw Error('Vui lòng chọn môn thi đấu.');if(!Array.isArray(body.rows))throw Error('Danh sách bảng đấu không hợp lệ.');if(body.rows.length>60)throw Error('Bảng đấu tối đa 60 dòng.');const rows=[];for(const row of body.rows){if(!Array.isArray(row)||row.length!==4)throw Error('Mỗi dòng bảng đấu cần đúng 4 ô.');const cells=row.map(c=>{if(typeof c!=='string')throw Error('Nội dung bảng đấu không hợp lệ.');const v=c.trim();if(v.length>200)throw Error('Mỗi ô bảng đấu tối đa 200 ký tự.');return v});if(cells.some(c=>c))rows.push(cells)}return {sport_id:body.sport_id,rows}}
